// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-7YBfLRQLL5skZrPQ2syjPCHp4wcQn0',
    appId: '1:502168257068:web:5d3af38de514527400c789',
    messagingSenderId: '502168257068',
    projectId: 'store-image-a4f19',
    authDomain: 'store-image-a4f19.firebaseapp.com',
    storageBucket: 'store-image-a4f19.appspot.com',
    measurementId: 'G-8MCCX5YSTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQkPLjhtD5sBXhR-rNl_eHhWB5FpkP-A',
    appId: '1:502168257068:android:8c385cdd1740a4b700c789',
    messagingSenderId: '502168257068',
    projectId: 'store-image-a4f19',
    storageBucket: 'store-image-a4f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAtc9qu6NDYHkSzPSv0ZuRiQFCRVwMBc',
    appId: '1:502168257068:ios:7c0acf4b4bb6000000c789',
    messagingSenderId: '502168257068',
    projectId: 'store-image-a4f19',
    storageBucket: 'store-image-a4f19.appspot.com',
    iosClientId: '502168257068-24ihs8d2a7h5phrvsdqa9t1at0la5kcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.anToanBaoMatTrongPtpmdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAtc9qu6NDYHkSzPSv0ZuRiQFCRVwMBc',
    appId: '1:502168257068:ios:7c0acf4b4bb6000000c789',
    messagingSenderId: '502168257068',
    projectId: 'store-image-a4f19',
    storageBucket: 'store-image-a4f19.appspot.com',
    iosClientId: '502168257068-24ihs8d2a7h5phrvsdqa9t1at0la5kcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.anToanBaoMatTrongPtpmdd',
  );
}
